name: Build macOS Application

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          brew install librsvg
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate icons
        run: |
          rsvg-convert -w 22 -h 22 icon.svg -o icon.png
          rsvg-convert -w 1024 -h 1024 icon.svg -o icon_1024.png
          mkdir -p icon.iconset
          sips -z 16 16 icon_1024.png --out icon.iconset/icon_16x16.png
          sips -z 32 32 icon_1024.png --out icon.iconset/icon_16x16@2x.png
          sips -z 32 32 icon_1024.png --out icon.iconset/icon_32x32.png
          sips -z 64 64 icon_1024.png --out icon.iconset/icon_32x32@2x.png
          sips -z 128 128 icon_1024.png --out icon.iconset/icon_128x128.png
          sips -z 256 256 icon_1024.png --out icon.iconset/icon_128x128@2x.png
          sips -z 256 256 icon_1024.png --out icon.iconset/icon_256x256.png
          sips -z 512 512 icon_1024.png --out icon.iconset/icon_256x256@2x.png
          sips -z 512 512 icon_1024.png --out icon.iconset/icon_512x512.png
          sips -z 1024 1024 icon_1024.png --out icon.iconset/icon_512x512@2x.png
          iconutil -c icns icon.iconset
          rm -rf icon.iconset
          rm icon_1024.png

      - name: Build application
        run: python setup.py py2app

      - name: Create DMG
        run: |
          mkdir -p dmg
          cp -r dist/Marmara\ Deprem.app dmg/
          hdiutil create -volname "Marmara Deprem" -srcfolder dmg -ov -format UDZO Marmara-Deprem.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: Marmara-Deprem
          path: |
            dist/Marmara Deprem.app
            Marmara-Deprem.dmg

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: |
            Marmara-Deprem.dmg
            dist/Marmara Deprem.app.zip
